### ISSUE TITLE
List OpenEXR as a dependency

### ISSUE THREAD

**Issue by chenzhekl** [JerryCao1985/SORT#97]
Hi, thanks for this great project! 

It looks like that `OpenEXR` is required for compiling the project. But it's not downloaded by the `getdep_xxx` script, nor is it listed on the website. Would you consider adding a line for it or replacing it with things like `tinyexr`?

**Comment by chenzhekl** [comment]
Oh, my bad. It's a dependency of OpenImageIO. Other things like `Boost` are also required then.

**Comment by JerryCao1985** [comment]
Not sure if you have solved the problem. Yes, building SORT on Ubuntu is a bit tricky comparing with other platforms. I haven't got the chance to update the building page yet, which I should have done right after supporting OSL.

I'll update it tomorrow to provide a better guide to build SORT on Ubuntu.

**Comment by chenzhekl** [comment]
Thanks for your reply! Yes, I succeeded in building SORT by manually installing all transient dependencies.

**Comment by JerryCao1985** [comment]
Awesome, may I know which version of Ubuntu you are using?

**Comment by chenzhekl** [comment]
Sure,

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

**Comment by JerryCao1985** [comment]
Good job.
BTW, I just updated the website with the latest guide of setting things up.
I still need to update my script to download the correct dependencies. I hope it helps.
